[env:nucleo_l432kc]
platform = ststm32
board = nucleo_l432kc
framework = stm32cube

; The Golden FPU Combination
build_flags =
    -I include
    -I lib/FreeRTOS/Source/include
    -I lib/FreeRTOS/Source/CMSIS_RTOS_V2
    -I lib/FreeRTOS/Source/portable/GCC/ARM_CM4F
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -Wl,-u,_printf_float

build_src_filter =
    +<*>
    +<../lib/FreeRTOS/Source/*.c>
    +<../lib/FreeRTOS/Source/CMSIS_RTOS_V2/*.c>
    +<../lib/FreeRTOS/Source/portable/GCC/ARM_CM4F/*.c>
    +<../lib/FreeRTOS/Source/portable/MemMang/heap_4.c>